### ISSUE TITLE
Enter确认候选项后，还多了个换行

### ISSUE THREAD

**Issue by calon** [JimmyHuang454/EasyCompleteYou#2]
Tab移动选中选项后，用Enter确认候选项，结果候选项上屏后，还多了一次换行。
如果用Ctrl-N/Ctrl-P，有时候可以选中后自动上屏，有时候又不行，感觉比较飘忽…

**Comment by JimmyHuang454** [comment]
你好！使用Tab选中选项即可，不需Enter确认，如果你需要展开snippet（如果有的话），请安装ultisnips后重启vim，选中一个选项就可以展开snippet，如果选中选项没有snippet可以展开，那么就会默认换行！

**Comment by calon** [comment]
感谢回复！

按 Tab 也命中不了，可以移到选项上，但选项不会自动上屏，所以一定要 Enter 才能上屏。
用的是默认配置，Tab 切换选项。
不知是否有选项可以在选中时就上屏，readme 中没有找到。

![screenshots](https://user-images.githubusercontent.com/501109/181135362-549f7191-315e-4f04-a76f-b67a69f26bf3.gif)

**Comment by JimmyHuang454** [comment]
> 感谢回复！
> 
> 按 Tab 也命中不了，可以移到选项上，但选项不会自动上屏，所以一定要 Enter 才能上屏。 用的是默认配置，Tab 切换选项。 不知是否有选项可以在选中时就上屏，readme 中没有找到。
> 
> ![screenshots](https://user-images.githubusercontent.com/501109/181135362-549f7191-315e-4f04-a76f-b67a69f26bf3.gif)

我白盒测试了一下（看github action），目前ECY符合预期行为， 我猜应该是你 `completeopt` 的问题（ECY在初始化时会把它设置成 `menu,preview`），使用 `echo &completeopt`即可查看你的设置，如果你的`completeopt`中包含了 `noinsert`，那么就意味着选中但不插入。

**Comment by calon** [comment]
感谢！已经解决了，撒花~

竟然忘了查 `completeopt` 选项，惭愧…
